service: simpply-back-node
frameworkVersion: "2"
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${opt:stage, 'local'}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
  serverless-offline:
    useChildProcesses: true

functions:
  api:
    handler: ./src/infrastructure/serverless/api.handler
    events:
      - http:
          path: /api
          method: ANY
      - http:
          path: /api/{proxy+}
          method: ANY
