app: simpply
service: simpply-back-node
frameworkVersion: "2"
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${opt:stage, 'local'}
    AIRTABLE__BASE_ID: ${env:AIRTABLE__BASE_ID, 'BASE_ID'}
    AIRTABLE__API_KEY: ${env:AIRTABLE__API_KEY, 'API_KEY'}
    AIRTABLE__API_TIMEOUT: ${env:AIRTABLE__API_TIMEOUT, '3000'}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
  serverless-offline:
    useChildProcesses: true

functions:
  api:
    handler: ./src/infrastructure/serverless/api.handler
    events:
      - http:
          path: /api
          method: ANY
      - http:
          path: /api/{proxy+}
          method: ANY
